### ISSUE TITLE
Unable to analyze single FASTQ reads

### ISSUE THREAD

**Issue by idolawoye** [Pathogen-Genomics-Cymru/lodestone#42]
Hi.

I am trying to analyze single reads but I am getting this error message:

WARN: Input tuple does not match input set cardinality declared by process `preprocessing:checkFqValidity` -- offending value: [ERR11243647, /home/olawoyei/projects/def-guthriej/olawoyei/mtb/fastq/ERR11243647.fastq.gz, /project/6083771/olawoyei/work/39/36be7d9f46f13a9a5a5d62ea719385/version.json]

Does lodestone only work with paired FASTQ reads?

**Comment by WhalleyT** [comment]
Hi @idolawoye sorry for the slow reply, I completely missed it. But yes, under the hood the pipeline makes calls to [Clockwork](https://github.com/iqbal-lab-org/clockwork) which assumes paired FASTQs
