### ISSUE TITLE
Additions for v0.9.8

### ISSUE THREAD

**Issue by annacprice** [Pathogen-Genomics-Cymru/lodestone#49]
- [x] Add compatibility for CLIMB Jupyter Notebooks (uses K8s/S3)
- [x] Replace gnomonicus with tb-profiler
- [x] Add csv output from mykrobe
- [x] Minor reporting bug fix (add missing publishDir statement to reAfanc and reKraken)
- [x] Publish full afanc report

**Comment by WhalleyT** [comment]
Turns out Mykrobe had a ```--output json_and_csv``` flag so I've added that in #51 and #52
