### ISSUE TITLE
TB-profiler issue v2

### ISSUE THREAD

**Issue by MarcNiebel** [Pathogen-Genomics-Cymru/lodestone#61]
Hi Tom, unfortunately this is still not working. Any ideas?
[error_log_lodestone_180624.txt](https://github.com/user-attachments/files/15886861/error_log_lodestone_180624.txt)

_Originally posted by @MarcNiebel in https://github.com/Pathogen-Genomics-Cymru/lodestone/issues/58#issuecomment-2176038050_

**Comment by MarcNiebel** [comment]
This is the tb-profiler error log if it is of any use.
[tbprofiler.errlog.txt](https://github.com/user-attachments/files/15887084/tbprofiler.errlog.txt)

**Comment by WhalleyT** [comment]
Hi again Marc, thanks for the continued efforts giving it a go! 

That's a new one to me, Just to double check, are the temporary files being written successfully? e.g. is something being written to ```./bcftools.0EDiR4``` like it says in the log?

**Comment by MarcNiebel** [comment]
Hi Tom, 
Using `find . -name "bcftools*"` in that specific working directory i.e. `8c/` yields no results. This is in contrast with the parent directory `work/` which does.

**Comment by MarcNiebel** [comment]
Ok thanks for looking into this. This is the command I am using ` nextflow run main.nf -profile singularity --input_dir MTB_WHO_sequences --pattern '*_R{1,2}_001.fastq.gz'`

**Comment by MarcNiebel** [comment]
Hi Tom, 
So that is actually what is happening when using singularity. The incorrect files are being grouped together so that is probably explaining the error.

**Comment by WhalleyT** [comment]
Ah right okay,. As a quick fix if you ```export TMPDIR="<new_tmp>"``` or ```export SINGULARITY_TMPDIR="<new_tmp>"``` to somewhere writable that should work, at least that was enough on my end :). The new version of tb-profiler allows you to pass a temporary directory as an argument (as do some of the other functions in the module) so I can make a parameter for it in the workflow so the user doesn't have to mess around with that

**Comment by MarcNiebel** [comment]
No worries. I will use Docker in the meantime  whilst  you sort the temporary directory as an argument .

**Comment by WhalleyT** [comment]
Hi again! I've added in a ```tmp_dir``` parameter in ```nextflow.config``` that specifies where tmp is for any of the tools in ```modules/vcfmixModules.nf``` that make use of them. I'll add them into the other places if this definitely works, but it's probably not priority as those containers don't have permission issues (they're all installed with pip et al. if that affects it?).

Please let me know how it goes, and if it works I'll add the ```tmp_dir``` to the rest of the pipeline. If this doesn't work I will try rebuilding the container and installing everything from scratch. I've tried to avoid this as tb-profiler's authors don't recommended it, but it might be more stable.

**Comment by WhalleyT** [comment]
Hi again! I've added in a tmp_dir parameter in nextflow.config that specifies where tmp is for any of the tools in modules/vcfmixModules.nf that make use of them. I'll add them into the other places if this definitely works, but it's probably not priority as those containers don't have permission issues (they're all installed with pip et al. if that affects it?).

Please let me know how it goes, and if it works I'll add the tmp_dir to the rest of the pipeline. If this doesn't work I will try rebuilding the container and installing everything from scratch. I've tried to avoid this as tb-profiler's authors don't recommended it, but it might be more stable.

**Comment by MarcNiebel** [comment]
Hi Tom, thanks for that. Will try it out in the coming days and keep  you informed of my progress

**Comment by WhalleyT** [comment]
Great, fingers crossed. Apologies as well last night I forgot to actually make the commit so it's on now.

**Comment by MarcNiebel** [comment]
Have tested it out on two samples and worked successfully. Checked the location of all files and they are grouped correctly 👍 
Thank you for sorting this out.

**Comment by WhalleyT** [comment]
Great stuff! Glad it worked. I'll close the issue for now but let me know  if anything else crops up :smile:
